services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, form types, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # loads services from whatever directories you want (you can add directories!)
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/{Command,Form,EventSubscriber,Twig,Security}'

    App\Controller\:
        resource: '../../src/Controller'
        public: true
        tags: ['controller.service_arguments']
