version: "3"

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    links:
      - php
    ports:
      - "80:80"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:5000"
        tag: "nginx"

  php:
    build: ./docker/php
    container_name: php-fpm
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - .:/var/www/html
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://127.0.0.1:5000"
    #     tag: "php-fpm"

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    command: ["--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]

volumes:
  db-volume:
